config/routes.rb
Rails.application.routes.draw do
  root "testes#index"
  resources :testes
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/teste.rb
class Teste < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/testes_controller.rb
class TestesController < ApplicationController

  before_action :set_testis, only: %i[ show edit update destroy ]

  # GET /testes or /testes.json
  def index
    @testes = Teste.all
  end

  # GET /testes/1 or /testes/1.json
  def show;
  end

  # GET /testes/new
  def new
    @testis = Teste.new
  end

  # GET /testes/1/edit
  def edit;
  end

  # POST /testes or /testes.json
  def create
    @testis = Teste.new(testis_params)

    respond_to do |format|
      if @testis.save
        format.html { redirect_to testis_url(@testis), notice: "Teste was successfully created." }
        format.json { render :show, status: :created, location: @testis }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testes/1 or /testes/1.json
  def update
    respond_to do |format|
      if @testis.update(testis_params)
        format.html { redirect_to testis_url(@testis), notice: "Teste was successfully updated." }
        format.json { render :show, status: :ok, location: @testis }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1 or /testes/1.json
  def destroy
    @testis.destroy

    respond_to do |format|
      format.html { redirect_to testes_url, notice: "Teste was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testis
      @testis = Teste.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def testis_params
      params.require(:testis).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoTeste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/testes/_form.html.erb
<%= form_with(model: testis) do |form| %>
  <% if testis.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
        <% testis.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/testes/_teste.html.erb
<div id="<%= dom_id teste %>">
  <p>
    <strong>Nome:</strong>
    <%= teste.nome %>
  </p>

</div>

app/views/testes/edit.html.erb
<h1>Editing teste</h1>

<%= render "form", testis: @testis %>

<br>

<div>
  <%= link_to "Show this teste", @testis %> |
  <%= link_to "Back to testes", testes_path %>
</div>

app/views/testes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Testes</h1>

<div id="testes">
  <% @testes.each do |testis| %>
    <%= render testis %>
    <p>
      <%= link_to "Show this teste", testis %>
    </p>
  <% end %>
</div>

<%= link_to "New teste", new_testis_path %>

app/views/testes/new.html.erb
<h1>New teste</h1>

<%= render "form", testis: @testis %>

<br>

<div>
  <%= link_to "Back to testes", testes_path %>
</div>

app/views/testes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @testis %>

<div>
  <%= link_to "Edit this teste", edit_testis_path(@testis) %> |
  <%= link_to "Back to testes", testes_path %>

  <%= button_to "Destroy this teste", @testis, method: :delete %>
</div>